name:  Run App and Capture Screenshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run App and Capture Screenshot
      run: |
        Start-Process -NoNewWindow -FilePath .\gradlew -ArgumentList "run"
        for ($i = 1; $i -le 18; $i++) {
          Start-Sleep -Seconds 10
          Add-Type -AssemblyName System.Drawing
          $bitmap = New-Object System.Drawing.Bitmap(800,600)
          $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
          $graphics.CopyFromScreen(0, 0, 0, 0, $bitmap.Size)
          $bitmap.Save("screenshot_$i.png", "PNG")
        }
        echo "Screenshots taken."

    - name: List Screenshots
      run: |
        dir screenshot_*.png
        echo "Screenshots listed."

    - name: Upload Screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        if-no-files-found: ignore  # 如果没有找到文件，则忽略此步骤
        path: screenshot_*.png

