name: Run Application

on:
  workflow_dispatch:

jobs:
  # Run on Windows
  run-on-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    name: Run On Windows
    steps:
      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 21

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # 设置工作目录
      - name: Set working directory
        run: |
          echo '${{ github.workspace }}'

      # Run App on Windows and capture screenshot using PowerShell
      - name: Run App on Windows and capture screenshot
        run: |
          # 运行应用程序，使其在后台运行
          Start-Process -NoNewWindow -FilePath ./gradlew -ArgumentList "run"
          
          # 循环10次，每次间隔10秒，获取屏幕截图
          for ($i = 1; $i -le 10; $i++) {
            Start-Sleep -Seconds 10
            # 截取屏幕截图，确保截图工具的命令适用于PowerShell
            # 此处需要替换为PowerShell中可用的截图命令
            # 示例：Add-Type -AssemblyName System.Drawing; [System.Drawing.Bitmap].FromFile("screenshot_$i.png")
          }


      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./*.png


