name: Run Distributable On macOS

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Distributable on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-latest]
        include:
          - os: macos-13
            arch: x64
            name: macOS x86_64
          - os: macos-latest
            arch: aarch64
            name: macOS aarch64
    env:
      ACTIONS_RUNNER_DEBUG: 'true'
      ACTIONS_STEP_DEBUG: 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java for macOS
        if: startsWith(matrix.os, 'macos')
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew

      - name: Install gtimeout on macOS
        run: |
          brew install coreutils  


      - name: Executing runDistributable with timeout for macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          ./gradlew runDistributable &
          sleep 300
          pkill -f "幕境"